"""initial schema

Revision ID: 38243fc0b8dd
Revises: 
Create Date: 2026-06-21 23:51:46.219181
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38243fc0b8dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('dur_min', sa.Float(), nullable=True),
    sa.Column('dist_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_activity_id'), ['activity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_activities_date'), ['date'], unique=False)

    op.create_table('bot_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_h', sa.Float(), nullable=True),
    sa.Column('deep_h', sa.Float(), nullable=True),
    sa.Column('rem_h', sa.Float(), nullable=True),
    sa.Column('light_h', sa.Float(), nullable=True),
    sa.Column('awake_h', sa.Float(), nullable=True),
    sa.Column('hrv_avg', sa.Integer(), nullable=True),
    sa.Column('hrv_status', sa.String(length=32), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('stress_max', sa.Integer(), nullable=True),
    sa.Column('bb_charged', sa.Integer(), nullable=True),
    sa.Column('bb_drained', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_date'), ['date'], unique=True)

    op.create_table('report_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_logs')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_date'))

    op.drop_table('daily_metrics')
    op.drop_table('bot_state')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_date'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_id'))

    op.drop_table('activities')
    # ### end Alembic commands ###
