"""add report_text to report_logs

Revision ID: 82431f3614e6
Revises: 38243fc0b8dd
Create Date: 2026-06-22 10:53:22.659285
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82431f3614e6'
down_revision: Union[str, None] = '38243fc0b8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_logs', schema=None) as batch_op:
        batch_op.drop_column('report_text')

    # ### end Alembic commands ###
