"""add cached flag to report_logs

Revision ID: 96bd35017bf1
Revises: 82431f3614e6
Create Date: 2026-06-22 10:57:33.773219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bd35017bf1'
down_revision: Union[str, None] = '82431f3614e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (SQLite can't add NOT NULL without it)
    with op.batch_alter_table('report_logs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('cached', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_logs', schema=None) as batch_op:
        batch_op.drop_column('cached')

    # ### end Alembic commands ###
